# Generated by Django 4.2.1 on 2023-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_project_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.ImageField(default=1, upload_to='projects'),
            preserve_default=False,
        ),
    ]
