# Generated by Django 4.2 on 2023-08-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_alter_project_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameModel(
            old_name='project',
            new_name='producto',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-creado'], 'verbose_name': ' Categoria ', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categories',
        ),
    ]
